server:
  port: 8080
spring:
  application:
    name: customs-transaction
  main:
    banner-mode: log
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
